### ISSUE TITLE
Link to OASIS site with company logos

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-open/csaf-documentation#14]
We could have a section where we show the logos of companies which are supporting CSAF. Would that be possible (from a legal point of view)?

**Comment by santosomar** [comment]
A better place for that is the official oasis tc website. There are a lot of permissions we will need to request.

**Comment by santosomar** [comment]
Probably a better approach (because of permissions, etc.) will be to have a link to the current members: https://www.oasis-open.org/committees/membership.php?wg_abbrev=csaf

We probably don't want to replicate the official OASIS TC website.

**Comment by santosomar** [comment]
Hi @tschmidtb51 - It turns out that OASIS does not have logos for all.. and some members do not belong to a company (individual contributors). I suggest to link to this instead: https://www.oasis-open.org/committees/membership.php?wg_abbrev=csaf

**Comment by santosomar** [comment]
For now, I have added a link to the member page under the main banner in the home page "[TC members](https://www.oasis-open.org/committees/membership.php?wg_abbrev=csaf) are working hard to standardize existing practice in structured machine-readable vulnerability-related advisories and further refine those standards over time."
