### ISSUE TITLE
Add links to public accessible presentations

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-open/csaf-documentation#17]
We should add links to the public accessible presentations / videos /slides /papers about CSAF 2.0. Currently, I'm aware of the following:
- [Your critical system IS (NOT?) vulnerable: CSAF, VEX, SBOM and the future of advisories](https://youtu.be/DCLvdwbHOVo)
- [CSAF 2.0 - A New Sstart to Automate Advisories](https://youtu.be/OMc8KJ6XVRI)

**Comment by santosomar** [comment]
Very good presentations! I will add them to the website today! Thank you!

**Comment by santosomar** [comment]
Done. Address in https://github.com/oasis-open/csaf-documentation/commit/8415beae55846880f807ace1776daece6902c0d2
