### ISSUE TITLE
Link to the schema instead of GitHub

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-open/csaf-documentation#20]
As we have the CSD in PR we should link to https://docs.oasis-open.org/csaf/csaf/v2.0/csaf_json_schema.json instead https://github.com/oasis-tcs/csaf/tree/master/csaf_2.0/json_schema. We should also consider to add the other (aggregator and provider-metadata) schemas somewhere.

**Comment by bernhardreiter** [comment]
This one is probably done for a while as urls ending with `json_schema` are not linked anymore.

Only https://docs.oasis-open.org/csaf/csaf/v2.0/os/schemas/ is.

Check:

```
git log --oneline | head -1
```
cae3994 Merge pull request #69 from oasis-open/repo-move-csaf_distribution
```bash
grep -r json_schema -l
history/project-220819152718.mobirise_history
history/project-210504211929.mobirise_history
history/project-210504212522.mobirise_history
history/project-220714210854.mobirise_history
history/project-220901182442.mobirise_history
history/project-220602194315.mobirise_history
history/project-210824160235.mobirise_history
history/project-220819152704.mobirise_history
history/project-220708121744.mobirise_history
history/project-220714210856.mobirise_history
```

```bash
 grep -r 'os/schemas' -l
tools.html
presentations.html
index.html
project.mobirise
webinar.html
specification.html
history/project-230901150544.mobirise_history
history/project-230912121657.mobirise_history
history/project-230901150549.mobirise_history

```

**Comment by bernhardreiter** [comment]
Would be better to exchange the link with https://docs.oasis-open.org/csaf/csaf/v2.0/errata01/os/schemas/ for now to get the updated aggregator schema.
