### ISSUE TITLE
Remove unmaintained software from the list

### ISSUE THREAD

**Issue by tschmidtb51** [oasis-open/csaf-documentation#38]
We should consider to remove currently unmaintained (or just CVRF supporting) software from the list of tools - or at least push them to the bottom. I guess that is the case for:
- [CSAF Parser](https://github.com/oasis-open/csaf-parser)
- [vulnrep](https://github.com/TIBCOSoftware/vulnrep)

@santosomar: Thoughts?

**Comment by santosomar** [comment]
I agree. I will work on the website redesign soon and will probably put a page just for tools and then make an "archive".
