### ISSUE TITLE
Conflict markers in examples/README.md

### ISSUE THREAD

**Issue by rgacogne** [oasis-open/csaf-documentation#41]
Hi,

There are git conflict markers in the current master (3617676e451d0eb21ac1792682e2535071e31bf6) version of examples/README.md, probably from a bad merge.

**Comment by santosomar** [comment]
I pointed https://csaf.io/examples to the CSAF TC examples and added the new [Explaining `x_generic_uris`](https://oasis-open.github.io/csaf-documentation/examples/x_generic_uris) post.
